version: '3.3'

services:
   nginx:
     image: zahav.azurecr.io/zahav/client:2.5-prod
     restart: always
     ports:
        - "80:80"
     environment:
        BE_PORT: 8000

   be:
     depends_on:
       - nginx
     image: zahav.azurecr.io/zahav/be:2.5-prod
     restart: always
     environment:
        BE_PORT: 8000
        FAULTS_DB_CONN_STRING: ${FAULTS_DB_CONN_STRING}
        USERS_DB_CONN_STRING: ${USERS_DB_CONN_STRING}
        USERS_TOKEN_SECRET: ${USERS_TOKEN_SECRET}